### PR TITLE
cranelift-simplejit: add a translation mechanism for LibCalls

### LINKED ISSUE #688: thread 'rustc' panicked at 'unexpected ExternalName kind %Memset'
This happens when using `FunctionBuilder::call_memset` and then calling `Module::finalize_definitions`.

### PR DESCRIPTION
**Pull request by antoyo**
Fix #688 by using a similar approach to #321.

### CODE REVIEW

File: cranelift-simplejit/src/backend.rs [hunk 1]
```diff
@@ -373,18 +418,27 @@ impl<'simple_jit_backend> Backend for SimpleJITBackend {
             let ptr = data.storage;
             debug_assert!((offset as usize) < data.size);
             let at = unsafe { ptr.offset(offset as isize) };
-            let base = if namespace.is_function(name) {
-                let (def, name_str, _signature) = namespace.get_function_definition(&name);
-                match def {
-                    Some(compiled) => compiled.code,
-                    None => self.lookup_symbol(name_str),
+            let base = match *name {
```
Comment (bnjbvr) [inline cranelift-simplejit/src/backend.rs]: Any chance this code can be factored out, since this is duplicated twice?

File: cranelift-simplejit/src/backend.rs [hunk 2]
```diff
@@ -21,17 +21,23 @@ use winapi;
...
 }
 
 impl SimpleJITBuilder {
     /// Create a new `SimpleJITBuilder`.
-    pub fn new() -> Self {
+    ///
+    /// The `libcall_names` function provides a way to translate `cranelift_codegen`'s `ir::LibCall`
+    /// enum to symbols. LibCalls are inserted in the IR as part of the legalization for certain
+    /// floating point instructions, and for stack probes. If you don't know what to use for this
+    /// argument, use `FaerieBuilder::default_libcall_names()`.
```
Comment (bnjbvr) [inline cranelift-simplejit/src/backend.rs]: In this comment and the one below, do you mean `SimpleJITBuilder::default_libcall_names()` instead?

**Comment by antoyo** [comment]
@bnjbvr: Thanks for your comments. I fixed this.

File: cranelift-simplejit/tests/basic.rs [hunk 3]
```diff
@@ -144,3 +150,53 @@ fn switch_error() {
...
+
+        bcx.call_memset(module.target_config(), buffer, zero, size);
+        module.finalize_definitions();
+
+        bcx.ins().return_(&[]);
+    }
+
+    module.define_function(func_id, &mut ctx).unwrap();
+
+    module.finalize_definitions();
```
Comment (bnjbvr) [inline cranelift-simplejit/tests/basic.rs]: It's a bit strange that `finalize_definitions()` can be called twice, but this is outside the scope of this bug. Can you remove the first call, that's a few lines above, please?

**Comment by bjorn3** [comment]
> @bjorn3 do you use the SimpleJit backend, or do you implement your own?

Yes, that's why I discovered #688. Currently `rustc_codegen_cranelift` can only run executables with absolutely no dependencies in jit mode though, but I want to fix that. (https://github.com/bjorn3/rustc_codegen_cranelift/issues/167)

**Comment by bnjbvr** [comment]
> Yes, that's why I discovered #688. Currently rustc_codegen_cranelift can only run executables with absolutely no dependencies in jit mode though, but I want to fix that. (bjorn3/rustc_codegen_cranelift#167)

Ok, in this case maybe we don't need to go full generic, and we can just hoist the default function to cranelift-module.

**Comment by antoyo** [comment]
@bnjbvr: I moved the default function to cranelift-module. Is there anything else to do?

**Comment by bnjbvr** [comment]
Looks good to me. (As an aside: TIL one can use `Box` et al. in a no-std build!)
Thanks!
