### PR TITLE
[frontend] Add message for pristine assertion violation

### LINKED ISSUE #1003: thread 'main' panicked at 'assertion failed: self.func_ctx.ebbs[ebb].pristine'
Cranelift panics if you try to add an EBB parameter after adding an instruction. It should give a verifier error or at least tell you that you need to declare all EBB parameters up front.

<details><summary>Reproduction steps</summary>

Assuming you have a `FunctionBuilder` in scope as `builder`:

```rust
use cranelift::codegen::ir::types;

let ebb = builder.create_ebb();
let ir_val = builder.append_ebb_param(ebb, types::I32);

// all of this is boilerplate for store()
let slot = builder.create_stack_slot(StackSlotData {
    kind: StackSlotKind::ExplicitSlot,
    size: 8,
    offset: None
});
let addr = builder.ins().stack_addr(types::I64, slot, 0);
builder.ins().store(MemFlags::new(), ir_val, addr, 0);

// panic occurs here
builder.append_ebb_param(ebb, types::I32);
```

</details>

<details><summary>Backtrace</summary>

```
thread 'main' panicked at 'assertion failed: self.func_ctx.ebbs[ebb].pristine', /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-frontend-0.42.0/src/frontend.rs:528:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: cranelift_frontend::frontend::FunctionBuilder::append_ebb_param
             at /home/joshua/.cargo/registry/src/github.com-1ecc6299db9ec823/cranelift-frontend-0.42.0/src/frontend.rs:528
// after this the backtrace is from my code and not helpful to you
```
</section>

### PR DESCRIPTION
**Pull request by walac**
After we add any instruction to an EBB, we can't add EBB parameters
anymore. There is an assertion in `append_ebb_param` to detect this
error, but the backtrace generated doesn't give any hint what happened.

We add an error message to the assertion so the user can understand what
is wrong.

fixes #1003

### CODE REVIEW

File: cranelift-frontend/src/frontend.rs [hunk 1]
```diff
@@ -523,7 +523,10 @@ impl FunctionBuilder {
     /// **Note:** this function has to be called at the creation of the `Ebb` before adding
     /// instructions to it, otherwise this could interfere with SSA construction.
     pub fn append_ebb_param(&mut self, ebb: Ebb, ty: Type) -> Value {
-        debug_assert!(self.func_ctx.ebbs[ebb].pristine);
+        debug_assert!(
+            self.func_ctx.ebbs[ebb].pristine,
+            "It can't add EBB parameters after adding any instruction"
```
Comment (bnjbvr) [inline cranelift-frontend/src/frontend.rs]: nit: the "It" at the beginning is uncommon in this code base, maybe we could either just remove it, or use an explicit "You can't add ..."?

Comment (walac) [reply cranelift-frontend/src/frontend.rs]: Done!
