### PR TITLE
Fix isplit legalization for ebb params when jumping forward

### LINKED ISSUE #1106: isplit.i128 not resolved when iconcat.i128 exists as part of a later legalized inst
```
test compile
target x86_64

function u0:0() -> i128 system_v {
ebb0:
    v0 = iconst.i64 0
    v1 = iconst.i64 0
    v2 = iconcat v0, v1
    jump ebb5

ebb2:
    jump ebb4(v27)

ebb4(v23: i128):
    return v23

ebb5:
    v27 = bxor.i128 v2, v2
    v32 = iconst.i32 0
    brz v32, ebb2
    trap user0
}
```

```
function u0:0() -> i64 [%rax], i64 [%rdx] system_v {
                                ebb0:
[RexOp1pu_id#b8]                    v0 = iconst.i64 0
[RexOp1pu_id#b8]                    v1 = iconst.i64 0
[-]                                 v2 = iconcat v0, v1
[Op1jmpb#eb]                        jump ebb5

                                ebb2:
[-]                                 v35, v36 = isplit.i128 v27
[Op1jmpb#eb]                        jump ebb4(v35, v36)
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
; error: inst4: v35 is a ghost value used by a real [Op1jmpb#eb] instruction


                                ebb4(v33: i64, v34: i64):
[-]                                 v23 = iconcat v33, v34
[Op1ret#c3]                         return v33, v34

                                ebb5:
[RexOp1rr#8031]                     v37 = bxor.i64 v0, v0
[RexOp1rr#8031]                     v38 = bxor.i64 v1, v1
[-]                                 v27 = iconcat v37, v38
[RexOp1pu_id#b8]                    v32 = iconst.i32 0
[RexOp1tjccb#74]                    brz v32, ebb2
[Op2trap#40b]                       trap user0
}

; 1 verifier error detected (see above). Compilation aborted.
```

### PR DESCRIPTION
**Pull request by bjorn3**
Fixes #1106

### CODE REVIEW

File: cranelift-codegen/src/legalizer/mod.rs [hunk 1]
```diff
@@ -65,6 +65,8 @@ fn legalize_inst(
     } else if opcode.is_branch() {
         split::simplify_branch_arguments(&mut pos.func.dfg, inst);
     } else if opcode == ir::Opcode::Isplit {
+        use crate::alloc::string::ToString;
+        dbg!(pos.func.dfg.display_inst(inst, isa).to_string());
```
Comment (abrown) [inline cranelift-codegen/src/legalizer/mod.rs]: Did you want to leave this `dbg!` in? Perhaps this could be a `debug!` or `trace!` log message with some explanatory text.

File: cranelift-codegen/src/legalizer/mod.rs [hunk 2]
```diff
@@ -145,6 +147,16 @@ pub fn legalize_function(func: &mut ir::Function, cfg: &mut ControlFlowGraph, is
...
+        // Split ebb params before trying to legalize instructions, so that the newly introduced
+        // isplit instructions get legalized.
+
+        let mut pos = FuncCursor::new(func);
+        while let Some(ebb) = pos.next_ebb() {
+            split::split_ebb_params(pos.func, cfg, ebb);
+        }
+    }
+
     let mut pos = FuncCursor::new(func);
```
Comment (abrown) [inline cranelift-codegen/src/legalizer/mod.rs]: Instead of making two of `FuncCursor` can we move lines 155-157 below this one? Or is there some ownership thing that prevents it?

File: cranelift-codegen/src/legalizer/mod.rs [hunk 3]
```diff
@@ -153,8 +165,6 @@ pub fn legalize_function(func: &mut ir::Function, cfg: &mut ControlFlowGraph, is
     // Process EBBs in layout order. Some legalization actions may split the current EBB or append
     // new ones to the end. We need to make sure we visit those new EBBs too.
     while let Some(ebb) = pos.next_ebb() {
-        split::split_ebb_params(pos.func, cfg, ebb);
-
```
Comment (abrown) [inline cranelift-codegen/src/legalizer/mod.rs]: Actually, now that I look at this I realize that I don't exactly understand what this is solving: why does splitting everything before this loop allow your test to compile?

Comment (abrown) [reply cranelift-codegen/src/legalizer/mod.rs]: Or in other words, why do we have to split above (with a separate `FuncCursor`) and not here?

File: cranelift-codegen/src/legalizer/mod.rs (hunk 1 above)
Comment (bjorn3) [reply cranelift-codegen/src/legalizer/mod.rs]: Forgot about it.

File: cranelift-codegen/src/legalizer/mod.rs (hunk 2 above)
Comment (bjorn3) [reply cranelift-codegen/src/legalizer/mod.rs]: Should be do-able.

File: cranelift-codegen/src/legalizer/mod.rs (hunk 3 above)
Comment (bjorn3) [reply cranelift-codegen/src/legalizer/mod.rs]: Taking the test as an example

Before when `ebb4` would get visited, `split_ebb_params` would insert an `isplit` before every jump to `ebb4`, as the jump in `ebb2` is before `ebb4`, the new `isplit` would never get legalized. After this PR, first all ebb params get split, introducing the necessary `isplit` and then all instructions get legalized, including the new `isplit`.

Comment (abrown) [reply cranelift-codegen/src/legalizer/mod.rs]: Ah, makes sense.

**Comment by bjorn3** [comment]
Squashed
